on:
  workflow_dispatch:
  push:
    branches:
      - radix-test

jobs:
  publish-latest:
    uses: ./.github/workflows/publish.yaml
    with:
      image-tag: latest
      oauth-redirect-url: https://proxy-development-framework-dev.radix.equinor.com
    secrets:
      ACR_SECRET: ${{ secrets.ACR_SECRET }}

  deploy:
    needs: publish-latest
    uses: ./.github/workflows/deploy.yaml
    with:
      radix-environment: 'dev'
    secrets:
      APP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.APP_SERVICE_ACCOUNT_TOKEN }}
