on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    needs: publish-latest
    uses: ./.github/workflows/deploy.yaml
    with:
      radix-environment: 'dev'
    secrets:
      APP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.APP_SERVICE_ACCOUNT_TOKEN }}
