on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  deploy:
    needs: publish-prod-tag
    uses: ./.github/workflows/deploy.yaml
    with:
      radix-environment: 'prod'
    secrets:
      APP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.APP_SERVICE_ACCOUNT_TOKEN }}
