on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  publish-latest:
    uses: ./.github/workflows/publish.yaml
    with:
      image-tag: latest
      oauth-redirect-url: https://development-framework.app.radix.equinor.com
    secrets:
      ACR_SECRET: ${{ secrets.ACR_SECRET }}

  deploy:
    needs: publish-latest
    uses: ./.github/workflows/deploy.yaml
    with:
      radix-environment: 'prod'
    secrets:
      APP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.APP_SERVICE_ACCOUNT_TOKEN }}
