on:
  workflow_dispatch:
  workflow_call:  # Workflow is meant to be called from another workflow, with the image tag as input
    inputs:
      image-tag:
        description: 'Which tag to set for the produced docker images'
        default: 'latest'
        required: true
        type: string
      oauth-redirect-url:
        description: 'redirect url for oauth. Should be the public url to access the web app'
        default: 'https://development-framework.app.radix.equinor.com'
        required: true
        type: string
    secrets:
      ACR_SECRET:
        required: false


env:
  IMAGE_REGISTRY: datamodelingtool.azurecr.io
  REGISTRY_USER: datamodelingtool
  NGINX_IMAGE: datamodelingtool.azurecr.io/dmt/dm-nginx
  DMT_IMAGE: datamodelingtool.azurecr.io/dmt/dmt

jobs:
  build-and-publish-nginx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: "Build and Publish nginx"
        run: |
          echo "Tagging with ${{ inputs.image-tag }}"
          docker login -u $REGISTRY_USER -p ${{ secrets.ACR_SECRET }} $IMAGE_REGISTRY
          docker build --cache-from $NGINX_IMAGE --tag $NGINX_IMAGE ./nginx
          docker push $NGINX_IMAGE:${{ inputs.image-tag }}

  build-and-publish-web-master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: "Build and Publish DMT"
        run: |
          echo "Tagging with ${{ inputs.image-tag }}"
          docker login -u $REGISTRY_USER -p ${{ secrets.ACR_SECRET }} $IMAGE_REGISTRY
          docker build \
          --build-arg REDIRECT_URI=${{inputs.oauth-redirect-url}} \
          --build-arg AUTH_ENABLED=1 \
          --build-arg AUTH_SCOPE=api://97a6b5bd-63fb-42c6-bb75-7e5de2394ba0/dmss \
          --build-arg CLIENT_ID=97a6b5bd-63fb-42c6-bb75-7e5de2394ba0 \
          --build-arg TENANT_ID=3aa4a235-b6e2-48d5-9195-7fcf05b459b0 \
          --tag ${DMT_IMAGE} \
          ./dmt
          docker tag $DMT_IMAGE $DMT_IMAGE:${{ inputs.image-tag }}
          docker push $DMT_IMAGE:${{ inputs.image-tag }}
